import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/storeProvider";
import { QueryProviders } from "@/reactQuery/QueryProvider";
import Navbar from "./_ui/navbar/Navbar";
import Header from "./_ui/header/Header";
import DataShopingCart from "./_ui/navbar/DataShopingCart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProviders>
            <StoreProvider >
              <header className="relative">
                <Navbar />
                <DataShopingCart/>
                <Header />
              </header>
              <main className="w-[90%] mx-auto">
                 {children}
              </main>
            </StoreProvider>
         </QueryProviders>

      </body>
    </html>
  );
}
